<a href="https://colab.research.google.com/github/alifia07nisa/data-science-2026/blob/main/Pertemuan3_Alifia_Choirunnisa_250401020010.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd, numpy as np
from scipy.stats.mstats import winsorize

In [3]:
URL = "https://drive.google.com/uc?export=download&id=1LfQWProB0VjWN5q8bKuRIgn-stULfIRo"
df = pd.read_csv(URL)
df.head()

   id  luas_m2  harga_juta   kota  kamar  tahun_bangun kondisi
0   1    297.0      1084.0  jogja    2.0          2000    baik
1   2    254.0       761.0  Medan    NaN          1995   Bagus
2   3    249.7       895.0  Depok    NaN          1983    baik
3   4     49.7       178.0    YGY    5.0          2013    baik
4   5    133.4       424.0  Medan    5.0          2004  Sedang

In [8]:
#Eksplorasi Awal
print('Shape awal:', df.shape)
print('Informasi :')
df.info()
print('Deskripsi :')
print(df.describe())
#Jumlah kolom yang memiliki nilai kosong
print('Kolom dengan nilai kosong :')
print(df.isnull().sum())

Shape awal: (130, 7)
Informasi :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            130 non-null    int64
 1   luas_m2       112 non-null    float64
 2   harga_juta    113 non-null    float64
 3   kota          130 non-null    object
 4   kamar         120 non-null    float64
 5   tahun_bangun  130 non-null    int64
 6   kondisi       130 non-null    object
dtypes: float64(3), int64(2), object(2)
memory usage: 7.2+ KB
Deskripsi :
               id      luas_m2    harga_juta       kamar  tahun_bangun
count  130.000000   112.000000  1.130000e+02  120.000000    130.000000
mean    65.500000   267.627679  8.856325e+05    3.433333   2062.638462
std     37.671829   885.664181  9.407144e+06    1.776283    701.684043
min      1.000000   -50.000000 -5.000000e+02    1.000000   1890.000000
25%     33.250000    87.050000  3.450000e+02    2.000000   1991.250000
50%     65.500000   193.800000  6.550000e+02    4.000000   2002.000000
75%     97.750000   280.675000  9.550000e+02    5.000000   2011.750000
max    130.000000  9500.000000  1.000000e+08    6.000000   9999.000000
Kolom dengan nilai kosong :
id               0
luas_m2         18
harga_juta      17
kota             0
kamar           10
tahun_bangun     0
kondisi          0
dtype: int64

In [9]:
#Hapus duplikat
df.drop_duplicates(inplace=True)
print('Setelah hapus duplikat:', df.shape)

Setelah hapus duplikat: (130, 7)

In [11]:
#Normalisasi string
df['kota'] = df['kota'].str.strip().str.title()
df['kondisi'] = df['kondisi'].str.strip().str.lower()

In [12]:
#Imputasi Missing Values
df['luas_m2'] = df['luas_m2'].fillna(df['luas_m2'].median())
df['harga_juta'] = df['harga_juta'].fillna(df['harga_juta'].median())
df['kamar'] = df['kamar'].fillna(df['kamar'].mode()[0])

In [13]:
#Tangani Outlier (IQR Fence)
for col in ['harga_juta', 'luas_m2', 'tahun_bangun']:
 Q1, Q3 = df[col].quantile([0.25, 0.75])
 IQR = Q3 - Q1
df[col] = df[col].clip(Q1-1.5*IQR, Q3+1.5*IQR)

In [14]:
#Validasi & Ekspor
assert df.isnull().sum().sum() == 0, 'Masih ada missing!'
assert df.duplicated().sum() == 0, 'Masih ada duplikat!'
print('Shape akhir:', df.shape)

Shape akhir: (130, 7)

In [15]:
#export
df.to_csv('housing_clean.csv', index=False)
print('Dataset bersih tersimpan!')

Dataset bersih tersimpan!

In [21]:
#JSON
import requests, pandas as pd
from pandas import json_normalize
import io # untuk membaca data string sebagai file

URL = "https://drive.google.com/uc?export=download&id=1LfQWProB0VjWN5q8bKuRIgn-stULfIRo"
response = requests.get(URL, timeout=10)

if response.status_code == 200:
    f = pd.read_csv(io.StringIO(response.text))
    display(df.head())
else:
    print(f'Error fetching URL: {response.status_code}')

   id  luas_m2  harga_juta   kota  kamar  tahun_bangun kondisi
0   1    297.0      1084.0  jogja    2.0          2000    baik
1   2    254.0       761.0  Medan    NaN          1995   Bagus
2   3    249.7       895.0  Depok    NaN          1983    baik
3   4     49.7       178.0    YGY    5.0          2013    baik
4   5    133.4       424.0  Medan    5.0          2004  Sedang

In [22]:
import requests, pandas as pd
from pandas import json_normalize
# ① Contoh: JSONPlaceholder (gratis, tanpa API key)
URL = "https://jsonplaceholder.typicode.com/users"
response = requests.get(URL, timeout=10)
# ② Selalu cek status code terlebih dahulu
if response.status_code == 200:
 data = response.json()
 df = json_normalize(data, sep='_')
 print(df[['id','name','email','address_city']])
else:
 print(f'Error: {response.status_code}')

   id                      name                      email    address_city
0   1             Leanne Graham          Sincere@april.biz     Gwenborough
1   2              Ervin Howell          Shanna@melissa.tv     Wisokyburgh
2   3          Clementine Bauch         Nathan@yesenia.net   McKenziehaven
3   4          Patricia Lebsack  Julianne.OConner@kory.org     South Elvis
4   5          Chelsey Dietrich   Lucio_Hettinger@annie.ca      Roscoeview
5   6      Mrs. Dennis Schulist    Karley_Dach@jasper.info   South Christy
6   7           Kurtis Weissnat     Telly.Hoeger@billy.biz       Howemouth
7   8  Nicholas Runolfsdottir V       Sherwood@rosamond.me       Aliyaview
8   9           Glenna Reichert    Chaim_McDermott@dana.io  Bartholomebury
9  10        Clementina DuBuque     Rey.Padberg@karina.biz     Lebsackbury